[workspace]
channels = ["conda-forge", "bioconda", "main", "r", "msys2"]
name = "varkit"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
"varkit-run" = "python3 ./src/main.py"

[dependencies]
cnvkit = "0.9.12.*"
python = "3.10.*"
bwa = "0.7.19.*"
samtools = "1.22.1.*"
gatk4 = "4.6.2.0.*"
snpeff = "5.2.*"
snpsift = "5.2.*"
seqtk = "1.5.*"
bcftools = "*"

[pypi-dependencies]
pyyaml = "*"
pandas = "*"
seaborn = "*"
cyvcf2 = "*"

[environments]
varkit = []
